import type { Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import './globals.css';
import Header from '@/components/ui/Header';

export const metadata: Metadata = {
  title: 'Notion-Clone',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
         <Header/>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
